// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CongressionalDistricts string
	SchemaMigrations       string
	StateFipsCodes         string
	States                 string
	UsCounties             string
	ZipCodes               string
}{
	CongressionalDistricts: "congressional_districts",
	SchemaMigrations:       "schema_migrations",
	StateFipsCodes:         "state_fips_codes",
	States:                 "states",
	UsCounties:             "us_counties",
	ZipCodes:               "zip_codes",
}
