// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testStates(t *testing.T) {
	t.Parallel()

	query := States()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testStatesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &State{}
	if err = randomize.Struct(seed, o, stateDBTypes, true, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := States().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStatesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &State{}
	if err = randomize.Struct(seed, o, stateDBTypes, true, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := States().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := States().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStatesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &State{}
	if err = randomize.Struct(seed, o, stateDBTypes, true, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StateSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := States().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStatesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &State{}
	if err = randomize.Struct(seed, o, stateDBTypes, true, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := StateExists(ctx, tx, o.Statefp)
	if err != nil {
		t.Errorf("Unable to check if State exists: %s", err)
	}
	if !e {
		t.Errorf("Expected StateExists to return true, but got false.")
	}
}

func testStatesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &State{}
	if err = randomize.Struct(seed, o, stateDBTypes, true, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	stateFound, err := FindState(ctx, tx, o.Statefp)
	if err != nil {
		t.Error(err)
	}

	if stateFound == nil {
		t.Error("want a record, got nil")
	}
}

func testStatesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &State{}
	if err = randomize.Struct(seed, o, stateDBTypes, true, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = States().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testStatesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &State{}
	if err = randomize.Struct(seed, o, stateDBTypes, true, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := States().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testStatesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	stateOne := &State{}
	stateTwo := &State{}
	if err = randomize.Struct(seed, stateOne, stateDBTypes, false, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}
	if err = randomize.Struct(seed, stateTwo, stateDBTypes, false, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = stateOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = stateTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := States().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testStatesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	stateOne := &State{}
	stateTwo := &State{}
	if err = randomize.Struct(seed, stateOne, stateDBTypes, false, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}
	if err = randomize.Struct(seed, stateTwo, stateDBTypes, false, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = stateOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = stateTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := States().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func stateBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *State) error {
	*o = State{}
	return nil
}

func stateAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *State) error {
	*o = State{}
	return nil
}

func stateAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *State) error {
	*o = State{}
	return nil
}

func stateBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *State) error {
	*o = State{}
	return nil
}

func stateAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *State) error {
	*o = State{}
	return nil
}

func stateBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *State) error {
	*o = State{}
	return nil
}

func stateAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *State) error {
	*o = State{}
	return nil
}

func stateBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *State) error {
	*o = State{}
	return nil
}

func stateAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *State) error {
	*o = State{}
	return nil
}

func testStatesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &State{}
	o := &State{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, stateDBTypes, false); err != nil {
		t.Errorf("Unable to randomize State object: %s", err)
	}

	AddStateHook(boil.BeforeInsertHook, stateBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	stateBeforeInsertHooks = []StateHook{}

	AddStateHook(boil.AfterInsertHook, stateAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	stateAfterInsertHooks = []StateHook{}

	AddStateHook(boil.AfterSelectHook, stateAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	stateAfterSelectHooks = []StateHook{}

	AddStateHook(boil.BeforeUpdateHook, stateBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	stateBeforeUpdateHooks = []StateHook{}

	AddStateHook(boil.AfterUpdateHook, stateAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	stateAfterUpdateHooks = []StateHook{}

	AddStateHook(boil.BeforeDeleteHook, stateBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	stateBeforeDeleteHooks = []StateHook{}

	AddStateHook(boil.AfterDeleteHook, stateAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	stateAfterDeleteHooks = []StateHook{}

	AddStateHook(boil.BeforeUpsertHook, stateBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	stateBeforeUpsertHooks = []StateHook{}

	AddStateHook(boil.AfterUpsertHook, stateAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	stateAfterUpsertHooks = []StateHook{}
}

func testStatesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &State{}
	if err = randomize.Struct(seed, o, stateDBTypes, true, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := States().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStatesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &State{}
	if err = randomize.Struct(seed, o, stateDBTypes, true); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(stateColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := States().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStateToManyStatefpCongressionalDistricts(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a State
	var b, c CongressionalDistrict

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, stateDBTypes, true, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, congressionalDistrictDBTypes, false, congressionalDistrictColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, congressionalDistrictDBTypes, false, congressionalDistrictColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.Statefp, a.Statefp)
	queries.Assign(&c.Statefp, a.Statefp)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.StatefpCongressionalDistricts().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.Statefp, b.Statefp) {
			bFound = true
		}
		if queries.Equal(v.Statefp, c.Statefp) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := StateSlice{&a}
	if err = a.L.LoadStatefpCongressionalDistricts(ctx, tx, false, (*[]*State)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.StatefpCongressionalDistricts); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.StatefpCongressionalDistricts = nil
	if err = a.L.LoadStatefpCongressionalDistricts(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.StatefpCongressionalDistricts); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testStateToManyAddOpStatefpCongressionalDistricts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a State
	var b, c, d, e CongressionalDistrict

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, stateDBTypes, false, strmangle.SetComplement(statePrimaryKeyColumns, stateColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*CongressionalDistrict{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, congressionalDistrictDBTypes, false, strmangle.SetComplement(congressionalDistrictPrimaryKeyColumns, congressionalDistrictColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*CongressionalDistrict{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddStatefpCongressionalDistricts(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.Statefp, first.Statefp) {
			t.Error("foreign key was wrong value", a.Statefp, first.Statefp)
		}
		if !queries.Equal(a.Statefp, second.Statefp) {
			t.Error("foreign key was wrong value", a.Statefp, second.Statefp)
		}

		if first.R.Statefp != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Statefp != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.StatefpCongressionalDistricts[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.StatefpCongressionalDistricts[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.StatefpCongressionalDistricts().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testStateToManySetOpStatefpCongressionalDistricts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a State
	var b, c, d, e CongressionalDistrict

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, stateDBTypes, false, strmangle.SetComplement(statePrimaryKeyColumns, stateColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*CongressionalDistrict{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, congressionalDistrictDBTypes, false, strmangle.SetComplement(congressionalDistrictPrimaryKeyColumns, congressionalDistrictColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetStatefpCongressionalDistricts(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.StatefpCongressionalDistricts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetStatefpCongressionalDistricts(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.StatefpCongressionalDistricts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.Statefp) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.Statefp) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.Statefp, d.Statefp) {
		t.Error("foreign key was wrong value", a.Statefp, d.Statefp)
	}
	if !queries.Equal(a.Statefp, e.Statefp) {
		t.Error("foreign key was wrong value", a.Statefp, e.Statefp)
	}

	if b.R.Statefp != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Statefp != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Statefp != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Statefp != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.StatefpCongressionalDistricts[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.StatefpCongressionalDistricts[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testStateToManyRemoveOpStatefpCongressionalDistricts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a State
	var b, c, d, e CongressionalDistrict

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, stateDBTypes, false, strmangle.SetComplement(statePrimaryKeyColumns, stateColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*CongressionalDistrict{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, congressionalDistrictDBTypes, false, strmangle.SetComplement(congressionalDistrictPrimaryKeyColumns, congressionalDistrictColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddStatefpCongressionalDistricts(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.StatefpCongressionalDistricts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveStatefpCongressionalDistricts(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.StatefpCongressionalDistricts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.Statefp) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.Statefp) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Statefp != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Statefp != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Statefp != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Statefp != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.StatefpCongressionalDistricts) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.StatefpCongressionalDistricts[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.StatefpCongressionalDistricts[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testStatesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &State{}
	if err = randomize.Struct(seed, o, stateDBTypes, true, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStatesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &State{}
	if err = randomize.Struct(seed, o, stateDBTypes, true, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StateSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStatesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &State{}
	if err = randomize.Struct(seed, o, stateDBTypes, true, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := States().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	stateDBTypes = map[string]string{`Gid`: `integer`, `Region`: `character varying`, `Division`: `character varying`, `Statefp`: `character varying`, `Statens`: `character varying`, `Geoid`: `character varying`, `Stusps`: `character varying`, `Name`: `character varying`, `Lsad`: `character varying`, `MTFCC`: `character varying`, `Funcstat`: `character varying`, `Aland`: `double precision`, `Awater`: `double precision`, `Intptlat`: `character varying`, `Intptlon`: `character varying`}
	_            = bytes.MinRead
)

func testStatesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(statePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(stateAllColumns) == len(statePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &State{}
	if err = randomize.Struct(seed, o, stateDBTypes, true, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := States().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, stateDBTypes, true, statePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testStatesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(stateAllColumns) == len(statePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &State{}
	if err = randomize.Struct(seed, o, stateDBTypes, true, stateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := States().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, stateDBTypes, true, statePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(stateAllColumns, statePrimaryKeyColumns) {
		fields = stateAllColumns
	} else {
		fields = strmangle.SetComplement(
			stateAllColumns,
			statePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := StateSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testStatesUpsert(t *testing.T) {
	t.Parallel()

	if len(stateAllColumns) == len(statePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := State{}
	if err = randomize.Struct(seed, &o, stateDBTypes, true); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert State: %s", err)
	}

	count, err := States().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, stateDBTypes, false, statePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize State struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert State: %s", err)
	}

	count, err = States().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
