// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testStateFipsCodes(t *testing.T) {
	t.Parallel()

	query := StateFipsCodes()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testStateFipsCodesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StateFipsCode{}
	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := StateFipsCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStateFipsCodesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StateFipsCode{}
	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := StateFipsCodes().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := StateFipsCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStateFipsCodesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StateFipsCode{}
	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StateFipsCodeSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := StateFipsCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStateFipsCodesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StateFipsCode{}
	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := StateFipsCodeExists(ctx, tx, o.Code)
	if err != nil {
		t.Errorf("Unable to check if StateFipsCode exists: %s", err)
	}
	if !e {
		t.Errorf("Expected StateFipsCodeExists to return true, but got false.")
	}
}

func testStateFipsCodesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StateFipsCode{}
	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	stateFipsCodeFound, err := FindStateFipsCode(ctx, tx, o.Code)
	if err != nil {
		t.Error(err)
	}

	if stateFipsCodeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testStateFipsCodesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StateFipsCode{}
	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = StateFipsCodes().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testStateFipsCodesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StateFipsCode{}
	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := StateFipsCodes().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testStateFipsCodesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	stateFipsCodeOne := &StateFipsCode{}
	stateFipsCodeTwo := &StateFipsCode{}
	if err = randomize.Struct(seed, stateFipsCodeOne, stateFipsCodeDBTypes, false, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}
	if err = randomize.Struct(seed, stateFipsCodeTwo, stateFipsCodeDBTypes, false, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = stateFipsCodeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = stateFipsCodeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := StateFipsCodes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testStateFipsCodesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	stateFipsCodeOne := &StateFipsCode{}
	stateFipsCodeTwo := &StateFipsCode{}
	if err = randomize.Struct(seed, stateFipsCodeOne, stateFipsCodeDBTypes, false, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}
	if err = randomize.Struct(seed, stateFipsCodeTwo, stateFipsCodeDBTypes, false, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = stateFipsCodeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = stateFipsCodeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StateFipsCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func stateFipsCodeBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *StateFipsCode) error {
	*o = StateFipsCode{}
	return nil
}

func stateFipsCodeAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *StateFipsCode) error {
	*o = StateFipsCode{}
	return nil
}

func stateFipsCodeAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *StateFipsCode) error {
	*o = StateFipsCode{}
	return nil
}

func stateFipsCodeBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *StateFipsCode) error {
	*o = StateFipsCode{}
	return nil
}

func stateFipsCodeAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *StateFipsCode) error {
	*o = StateFipsCode{}
	return nil
}

func stateFipsCodeBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *StateFipsCode) error {
	*o = StateFipsCode{}
	return nil
}

func stateFipsCodeAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *StateFipsCode) error {
	*o = StateFipsCode{}
	return nil
}

func stateFipsCodeBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *StateFipsCode) error {
	*o = StateFipsCode{}
	return nil
}

func stateFipsCodeAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *StateFipsCode) error {
	*o = StateFipsCode{}
	return nil
}

func testStateFipsCodesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &StateFipsCode{}
	o := &StateFipsCode{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize StateFipsCode object: %s", err)
	}

	AddStateFipsCodeHook(boil.BeforeInsertHook, stateFipsCodeBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	stateFipsCodeBeforeInsertHooks = []StateFipsCodeHook{}

	AddStateFipsCodeHook(boil.AfterInsertHook, stateFipsCodeAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	stateFipsCodeAfterInsertHooks = []StateFipsCodeHook{}

	AddStateFipsCodeHook(boil.AfterSelectHook, stateFipsCodeAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	stateFipsCodeAfterSelectHooks = []StateFipsCodeHook{}

	AddStateFipsCodeHook(boil.BeforeUpdateHook, stateFipsCodeBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	stateFipsCodeBeforeUpdateHooks = []StateFipsCodeHook{}

	AddStateFipsCodeHook(boil.AfterUpdateHook, stateFipsCodeAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	stateFipsCodeAfterUpdateHooks = []StateFipsCodeHook{}

	AddStateFipsCodeHook(boil.BeforeDeleteHook, stateFipsCodeBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	stateFipsCodeBeforeDeleteHooks = []StateFipsCodeHook{}

	AddStateFipsCodeHook(boil.AfterDeleteHook, stateFipsCodeAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	stateFipsCodeAfterDeleteHooks = []StateFipsCodeHook{}

	AddStateFipsCodeHook(boil.BeforeUpsertHook, stateFipsCodeBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	stateFipsCodeBeforeUpsertHooks = []StateFipsCodeHook{}

	AddStateFipsCodeHook(boil.AfterUpsertHook, stateFipsCodeAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	stateFipsCodeAfterUpsertHooks = []StateFipsCodeHook{}
}

func testStateFipsCodesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StateFipsCode{}
	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StateFipsCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStateFipsCodesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StateFipsCode{}
	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(stateFipsCodeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := StateFipsCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStateFipsCodesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StateFipsCode{}
	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStateFipsCodesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StateFipsCode{}
	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StateFipsCodeSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStateFipsCodesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &StateFipsCode{}
	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := StateFipsCodes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	stateFipsCodeDBTypes = map[string]string{`Name`: `text`, `Abbreviation`: `text`, `Code`: `text`}
	_                    = bytes.MinRead
)

func testStateFipsCodesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(stateFipsCodePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(stateFipsCodeAllColumns) == len(stateFipsCodePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &StateFipsCode{}
	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StateFipsCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true, stateFipsCodePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testStateFipsCodesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(stateFipsCodeAllColumns) == len(stateFipsCodePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &StateFipsCode{}
	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true, stateFipsCodeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := StateFipsCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, stateFipsCodeDBTypes, true, stateFipsCodePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(stateFipsCodeAllColumns, stateFipsCodePrimaryKeyColumns) {
		fields = stateFipsCodeAllColumns
	} else {
		fields = strmangle.SetComplement(
			stateFipsCodeAllColumns,
			stateFipsCodePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := StateFipsCodeSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testStateFipsCodesUpsert(t *testing.T) {
	t.Parallel()

	if len(stateFipsCodeAllColumns) == len(stateFipsCodePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := StateFipsCode{}
	if err = randomize.Struct(seed, &o, stateFipsCodeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert StateFipsCode: %s", err)
	}

	count, err := StateFipsCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, stateFipsCodeDBTypes, false, stateFipsCodePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize StateFipsCode struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert StateFipsCode: %s", err)
	}

	count, err = StateFipsCodes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
